<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="33" passed="27">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="447004" started-at="2019-02-08T15:37:31Z" finished-at="2019-02-08T15:44:58Z">
    <groups>
    </groups>
    <test name="Regression1" duration-ms="447004" started-at="2019-02-08T15:37:31Z" finished-at="2019-02-08T15:44:58Z">
      <class name="Test.google">
        <test-method status="PASS" signature="validateLoginWithInValidCredentials()[pri:0, instance:Test.google@5afa04c]" name="validateLoginWithInValidCredentials" duration-ms="14150" started-at="2019-02-08T21:09:48Z" finished-at="2019-02-08T21:10:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidCredentials -->
        <test-method status="PASS" signature="validateLoginWithInValidUserName()[pri:0, instance:Test.google@5afa04c]" name="validateLoginWithInValidUserName" duration-ms="14202" started-at="2019-02-08T21:10:02Z" finished-at="2019-02-08T21:10:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidUserName -->
        <test-method status="PASS" signature="validateLoginWithValidCredentials()[pri:0, instance:Test.google@5afa04c]" name="validateLoginWithValidCredentials" duration-ms="16732" started-at="2019-02-08T21:10:16Z" finished-at="2019-02-08T21:10:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithValidCredentials -->
        <test-method status="PASS" signature="validateSearchAcountByEmail()[pri:0, instance:Test.google@5afa04c]" name="validateSearchAcountByEmail" duration-ms="11566" started-at="2019-02-08T21:10:33Z" finished-at="2019-02-08T21:10:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByEmail -->
        <test-method status="PASS" signature="validateSearchAcountByImage()[pri:0, instance:Test.google@5afa04c]" name="validateSearchAcountByImage" duration-ms="8148" started-at="2019-02-08T21:10:45Z" finished-at="2019-02-08T21:10:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByImage -->
        <test-method status="FAIL" signature="validateSearchAcountByName()[pri:0, instance:Test.google@5afa04c]" name="validateSearchAcountByName" duration-ms="9212" started-at="2019-02-08T21:10:53Z" finished-at="2019-02-08T21:11:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.google.validateSearchAcountByName(google.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByName -->
        <test-method status="PASS" signature="validateSearchAcountByPhone()[pri:0, instance:Test.google@5afa04c]" name="validateSearchAcountByPhone" duration-ms="11573" started-at="2019-02-08T21:11:02Z" finished-at="2019-02-08T21:11:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByPhone -->
        <test-method status="PASS" signature="validateSearchUserByEmail()[pri:0, instance:Test.google@5afa04c]" name="validateSearchUserByEmail" duration-ms="12944" started-at="2019-02-08T21:11:14Z" finished-at="2019-02-08T21:11:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByEmail -->
        <test-method status="PASS" signature="validateSearchUserByImage()[pri:0, instance:Test.google@5afa04c]" name="validateSearchUserByImage" duration-ms="7023" started-at="2019-02-08T21:11:26Z" finished-at="2019-02-08T21:11:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByImage -->
        <test-method status="FAIL" signature="validateSearchUserByName()[pri:0, instance:Test.google@5afa04c]" name="validateSearchUserByName" duration-ms="9375" started-at="2019-02-08T21:11:34Z" finished-at="2019-02-08T21:11:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.google.validateSearchUserByName(google.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByName -->
        <test-method status="PASS" signature="validateSearchUserByPhone()[pri:0, instance:Test.google@5afa04c]" name="validateSearchUserByPhone" duration-ms="15111" started-at="2019-02-08T21:11:43Z" finished-at="2019-02-08T21:11:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByPhone -->
      </class> <!-- Test.google -->
      <class name="Test.bing">
        <test-method status="PASS" signature="validateLoginWithInValidCredentials()[pri:0, instance:Test.bing@174d20a]" name="validateLoginWithInValidCredentials" duration-ms="17651" started-at="2019-02-08T21:07:31Z" finished-at="2019-02-08T21:07:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidCredentials -->
        <test-method status="PASS" signature="validateLoginWithInValidUserName()[pri:0, instance:Test.bing@174d20a]" name="validateLoginWithInValidUserName" duration-ms="15302" started-at="2019-02-08T21:07:48Z" finished-at="2019-02-08T21:08:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidUserName -->
        <test-method status="PASS" signature="validateLoginWithValidCredentials()[pri:0, instance:Test.bing@174d20a]" name="validateLoginWithValidCredentials" duration-ms="17701" started-at="2019-02-08T21:08:04Z" finished-at="2019-02-08T21:08:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithValidCredentials -->
        <test-method status="PASS" signature="validateSearchAcountByEmail()[pri:0, instance:Test.bing@174d20a]" name="validateSearchAcountByEmail" duration-ms="12393" started-at="2019-02-08T21:08:21Z" finished-at="2019-02-08T21:08:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByEmail -->
        <test-method status="PASS" signature="validateSearchAcountByImage()[pri:0, instance:Test.bing@174d20a]" name="validateSearchAcountByImage" duration-ms="8064" started-at="2019-02-08T21:08:34Z" finished-at="2019-02-08T21:08:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByImage -->
        <test-method status="FAIL" signature="validateSearchAcountByName()[pri:0, instance:Test.bing@174d20a]" name="validateSearchAcountByName" duration-ms="9766" started-at="2019-02-08T21:08:42Z" finished-at="2019-02-08T21:08:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.bing.validateSearchAcountByName(bing.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByName -->
        <test-method status="PASS" signature="validateSearchAcountByPhone()[pri:0, instance:Test.bing@174d20a]" name="validateSearchAcountByPhone" duration-ms="12499" started-at="2019-02-08T21:08:52Z" finished-at="2019-02-08T21:09:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByPhone -->
        <test-method status="PASS" signature="validateSearchUserByEmail()[pri:0, instance:Test.bing@174d20a]" name="validateSearchUserByEmail" duration-ms="12170" started-at="2019-02-08T21:09:04Z" finished-at="2019-02-08T21:09:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByEmail -->
        <test-method status="PASS" signature="validateSearchUserByImage()[pri:0, instance:Test.bing@174d20a]" name="validateSearchUserByImage" duration-ms="7195" started-at="2019-02-08T21:09:16Z" finished-at="2019-02-08T21:09:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByImage -->
        <test-method status="FAIL" signature="validateSearchUserByName()[pri:0, instance:Test.bing@174d20a]" name="validateSearchUserByName" duration-ms="10300" started-at="2019-02-08T21:09:24Z" finished-at="2019-02-08T21:09:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.bing.validateSearchUserByName(bing.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByName -->
        <test-method status="PASS" signature="validateSearchUserByPhone()[pri:0, instance:Test.bing@174d20a]" name="validateSearchUserByPhone" duration-ms="14153" started-at="2019-02-08T21:09:34Z" finished-at="2019-02-08T21:09:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByPhone -->
      </class> <!-- Test.bing -->
      <class name="Test.yahoo">
        <test-method status="PASS" signature="validateLoginWithInValidCredentials()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateLoginWithInValidCredentials" duration-ms="14598" started-at="2019-02-08T21:11:58Z" finished-at="2019-02-08T21:12:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidCredentials -->
        <test-method status="PASS" signature="validateLoginWithInValidUserName()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateLoginWithInValidUserName" duration-ms="15301" started-at="2019-02-08T21:12:13Z" finished-at="2019-02-08T21:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidUserName -->
        <test-method status="PASS" signature="validateLoginWithValidCredentials()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateLoginWithValidCredentials" duration-ms="17436" started-at="2019-02-08T21:12:28Z" finished-at="2019-02-08T21:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithValidCredentials -->
        <test-method status="PASS" signature="validateSearchAcountByEmail()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchAcountByEmail" duration-ms="15406" started-at="2019-02-08T21:12:45Z" finished-at="2019-02-08T21:13:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByEmail -->
        <test-method status="PASS" signature="validateSearchAcountByImage()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchAcountByImage" duration-ms="13195" started-at="2019-02-08T21:13:01Z" finished-at="2019-02-08T21:13:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByImage -->
        <test-method status="FAIL" signature="validateSearchAcountByName()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchAcountByName" duration-ms="11469" started-at="2019-02-08T21:13:14Z" finished-at="2019-02-08T21:13:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.yahoo.validateSearchAcountByName(yahoo.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByName -->
        <test-method status="PASS" signature="validateSearchAcountByPhone()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchAcountByPhone" duration-ms="24184" started-at="2019-02-08T21:13:25Z" finished-at="2019-02-08T21:13:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchAcountByPhone -->
        <test-method status="PASS" signature="validateSearchUserByEmail()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchUserByEmail" duration-ms="13580" started-at="2019-02-08T21:13:50Z" finished-at="2019-02-08T21:14:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByEmail -->
        <test-method status="PASS" signature="validateSearchUserByImage()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchUserByImage" duration-ms="14815" started-at="2019-02-08T21:14:03Z" finished-at="2019-02-08T21:14:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByImage -->
        <test-method status="FAIL" signature="validateSearchUserByName()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchUserByName" duration-ms="12939" started-at="2019-02-08T21:14:18Z" finished-at="2019-02-08T21:14:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is my failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is my failure
	at org.testng.Assert.fail(Assert.java:93)
	at Test.yahoo.validateSearchUserByName(yahoo.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByName -->
        <test-method status="PASS" signature="validateSearchUserByPhone()[pri:0, instance:Test.yahoo@7921b0a2]" name="validateSearchUserByPhone" duration-ms="26771" started-at="2019-02-08T21:14:31Z" finished-at="2019-02-08T21:14:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSearchUserByPhone -->
      </class> <!-- Test.yahoo -->
    </test> <!-- Regression1 -->
  </suite> <!-- Suite1 -->
</testng-results>
